### PR TITLE
Enable colors for non-tty stdout

### PR DESCRIPTION
**Pull request by kingcody**
see Marak/colors.js#102

### CODE REVIEW

**Comment by jwalton** [comment]
Hrm...  No color for TTY output is desirable in most cases, though; if you're piping your logs to a file, you probably don't want color in there.  It would be nice if we could leave colors off for non-tty output by default, but turn it on if someone passed in an appropriate option (say, `forceColor`) to BunyanDebugStream.  The problem here is that we're setting a global variable in `colors` to do this, so  if you create two BunyanDebugStreams, one with `forceColor` and one without, they'd both show colors (although I suppose you'd probably never do this...)

**Comment by jwalton** [comment]
Fixed in v1.0.7 with `forceColor` option.

**Comment by kingcody** [comment]
@jwalton thanks! Sorry for the shortsightedness with the option being globally persistent.

**Comment by jwalton** [comment]
No worries.  Thanks for figuring this out.  :)

**Pull request closed without merging**
